spring.application.name=blast-radius-worker

# The AI Connection (Notice the .options. in the middle!)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=deepseek-coder


# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.ai.ollama.chat.temperature=0.0
spring.ai.ollama.chat.options.format=json